name: Exploit Workflow
on:
  push:
    branches: [ main ]
permissions:
  id-token: write
  contents: read
jobs:
  exploit:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::383574875380:role/new-challenge-role
          aws-region: ap-east-1
          role-session-name: ctf-ecr-session
          audience: sts.amazonaws.com
          output-env-credentials: true
